export const AuthExceptions = {
  ALREDY_REGISTERED: 'User with this credentials already exists!',
  USER_NOT_FOUND: 'User with this credentials not found!',
  USERS_NOT_FOUND: 'Users with this credentials not found!',
  PASSWORD_DOES_NOT_MATCH: 'Password does not match!!',
  WRONG_PASSWORD: 'Incorrect password',
  REFRESHTOKEN_NOT_FOUND: 'Resresh token not found!',
  TOKEN_FAULT: 'The token was not found or the token is not valid',
  CODE_NOT_CORRECT: 'The code is not correct!',
  ACCESS_DENIED: 'access denied',
  TIME_HAS_EZPIRIED: 'The time for password recovery has expired',
  EMAIL_NOT_CONFIRM: 'You have not confirmed email',
  UNREGISTERED: 'Unregistered',
  USER_DO_NOT_HAVE_INFO: 'The user has no personal information',
  NOT_FOUND: 'Not found',
  DO_NOT_DELETE_ACCOUNT:
    'It is impossible to delete an account because there is no personal information about the user',
  SESSIONS_NOT_FOUND: 'Nothing not tothing was found for your query!',
  SLOT_IS_FULL: 'The slot is full',
  ALREDY_SIGNET: 'You have already signed up for this session',
  NOT_SUBSCRIBED: 'You are not subscribed to this session!',
  NOT_SUBSRIBE_NEXT_SESSION:
    'You can not sign up for a session because you did not leave a review from the previous one',
  MANAGER_SLOT_NOT_FOUND: 'Manager slot not found',
};
